# Generated by Django 4.2.6 on 2023-10-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tel_raqam',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
